spring:
  application:
    name: user-api-service
  rabbitmq:
    host: rabbitmq
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_DEFAULT_USER}
    password: ${RABBITMQ_DEFAULT_PASS}
    queue:
      name: ${RABBITMQ_QUEUE_EMAIL_NAME}
      key: ${RABBITMQ_QUEUE_EMAIL_KEY}
    exchange:
      name: ${RABBITMQ_EXCHANGE_NAME}

  data:
    redis:
      host: redis
      port: ${REDIS_PORT}
      timeout: ${REDIS_TIMEOUT}

jwt:
  secret: ${JWT_SECRET}
  lifetime: ${JWT_LIFETIME}

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:${SERVICE_DISCOVERY_PORT}/eureka
    register-with-eureka: true
    fetch-registry: true

server:
  port: ${USER_API_SERVICE_PORT}

grpc:
  client:
    grpc-service:
      address: 'discovery:///database-service'
      negotiation-type: plaintext
