spring:
  application:
    name: user-api-service
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: bestuser
    password: bestuser
  data:
    redis:
      host: redis
      port: 6379
      timeout: 100000

jwt:
  secret: jeXWnV9fY7BPLPEuJaBnJVETR1M5pSpXtDmnqy1KK1py+gLvFCMe1u84F8t5ZkNH
  lifetime: 600000

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka
    register-with-eureka: true
    fetch-registry: true

server:
  port: 0
grpc:
  client:
    grpc-service:
      address: 'discovery:///database-service'
      negotiation-type: plaintext
