spring:
  application:
    name: email-sender-service

  rabbitmq:
    host: rabbitmq
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_DEFAULT_USER}
    password: ${RABBITMQ_DEFAULT_PASS}
    queue:
      name: ${RABBITMQ_QUEUE_EMAIL_NAME}
      key: ${RABBITMQ_QUEUE_EMAIL_KEY}
    exchange:
      name: ${RABBITMQ_EXCHANGE_NAME}

  mail:
    host: ${SPRING_MAIL_HOST}
    port: ${SPRING_MAIL_PORT}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    subject: ${SPRING_MAIL_SUBJECT}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:${SERVICE_DISCOVERY_PORT}/eureka
    register-with-eureka: true
    fetch-registry: false

server:
  port: ${EMAIL_SENDER_SERVICE_PORT}