spring:
  application:
    name: database-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/ens
    username: bestuser
    password: bestuser
  jpa:
    database: postgresql
    show-sql: true
  liquibase:
    change-log: db/changelog/main/main-changelog.yml

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka

server:
  port: 0