spring:
  application:
    name: database-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:${POSTGRES_PORT}/${POSTGRES_DATABASE}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    database: postgresql
    show-sql: true
  liquibase:
    change-log: db/changelog/main/main-changelog.yml

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:${SERVICE_DISCOVERY_PORT}/eureka
    register-with-eureka: true
    fetch-registry: false

server:
  port: ${DATABASE_SERVICE_PORT}

grpc:
  server:
    port: ${DATABASE_SERVICE_GRPC_SERVER_PORT}

springdoc:
  api-docs:
    path: /api-docs