spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
        - id: user-api-service
          uri: lb://user-api-service
          predicates:
            - Path=/ens/**

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka

logging:
  level:
    root: INFO
    org:
      springframework:
        cloud:
          gateway:
            route:
              RouteDefinitionLocator: INFO

server:
  port: 8080