version: '3.7'

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_DB: ens
      POSTGRES_USER: bestuser
      POSTGRES_PASSWORD: bestuser
    volumes:
      - D:\postgres_datapart:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    environment:
      - REDIS_PORT=6379
      - REDIS_DATABASES=1

  discovery-service:
    container_name: discovery-service
    build: /discovery-service/.
    pull_policy: always
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  api-gateway-service:
    build: /api-gateway-service/.
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - discovery-service

  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=bestuser
      - RABBITMQ_DEFAULT_PASS=bestuser
    ports:
      - "5672:5672"

  user-api-service:
    container_name: user-api-service
    build: /user-api-service/.
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - rabbitmq
      - api-gateway-service
      - database-service

  database-service:
    container_name: database-service
    build: database-service/.
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/ens
    depends_on:
      - api-gateway-service
      - postgres

  email-sender-service:
    container_name: email-sender-service
    build: email-sender-service/.
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - user-api-service