version: '3.7'

services:

  discovery-service:
    container_name: discovery-service
    build: /discovery-service/.
    pull_policy: always
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
